# Generated by Django 6.1.1 on 2026-09-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('restablecimiento', 'Solicitud de restablecimiento')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['accion', 'email', 'creado_en'], name='ciudadania__accion_dbd2da_idx')],
            },
        ),
    ]
