# Generated by Django 6.1.1 on 2026-09-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadania', '0002_intentoacceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentoacceso',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('restablecimiento', 'Solicitud de restablecimiento'), ('reenvio_verificacion', 'Reenvío de verificación de correo')], max_length=20),
        ),
    ]
