# Generated by Django 6.1.1 on 2026-09-15 23:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadania', '0003_alter_intentoacceso_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoExpediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('satelite_origen', models.CharField(max_length=50)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_expediente', to='ciudadania.ciudadano')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['ciudadano', 'satelite_origen', 'creado_en'], name='ciudadania__ciudada_d75e03_idx')],
            },
        ),
    ]
