# Generated by Django 6.1.1 on 2026-09-16 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadania', '0006_semilla_tipos_de_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoProceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('satelite_origen', models.CharField(max_length=50)),
                ('referencia_proceso', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('url_relativa', models.CharField(blank=True, default='', max_length=500)),
                ('pasos_completados', models.JSONField(blank=True, default=list)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_proceso', to='ciudadania.ciudadano')),
            ],
            options={
                'ordering': ['-actualizado_en'],
                'indexes': [models.Index(fields=['ciudadano', 'satelite_origen', 'referencia_proceso', 'estado'], name='ciudadania__ciudada_bb547c_idx')],
            },
        ),
    ]
